// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinancialControl.DATA.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public DateTime TransactionDate { get; set; }

    public decimal TransactionValue { get; set; }

    public string TransactionDescription { get; set; }

    public int TransactionIdPaymentMethod { get; set; }

    public int TransactionIdCategory { get; set; }

    public virtual Category TransactionIdCategoryNavigation { get; set; }

    public virtual PaymentMethod TransactionIdPaymentMethodNavigation { get; set; }
}