// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinancialControl.DATA.Models;

public partial class VwTransactionDetail
{
    public string CategoryName { get; set; }

    public string PaymentMethod { get; set; }

    public int Id { get; set; }

    public DateTime TransactionDate { get; set; }

    public string TransactionDescription { get; set; }

    public int TransactionIdCategory { get; set; }

    public int TransactionIdPaymentMethod { get; set; }

    public decimal TransactionValue { get; set; }
}